# Generated by Django 5.2.11 on 2026-02-07 20:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision_point', models.TextField(help_text='What decision was being made')),
                ('options_considered', models.JSONField(help_text='List of options evaluated')),
                ('chosen_option', models.CharField(max_length=500)),
                ('reasoning', models.TextField(help_text='Why this option was chosen')),
                ('outcome', models.CharField(blank=True, choices=[('successful', 'Successful'), ('failed', 'Failed'), ('abandoned', 'Abandoned')], max_length=20, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='investigations.investigation')),
            ],
            options={
                'db_table': 'agent_decisions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['investigation', 'timestamp'], name='agent_decis_investi_d42668_idx')],
            },
        ),
        migrations.CreateModel(
            name='ThoughtChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField(help_text='Order in the thought chain')),
                ('thought_type', models.CharField(choices=[('hypothesis', 'Hypothesis'), ('question', 'Question'), ('observation', 'Observation'), ('conclusion', 'Conclusion'), ('correction', 'Correction')], max_length=20)),
                ('content', models.TextField(help_text='The actual thought/reasoning')),
                ('confidence_before', models.FloatField(default=0.5)),
                ('confidence_after', models.FloatField(default=0.5)),
                ('gemini_thought_signature', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thoughts', to='investigations.investigation')),
                ('led_to_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thoughts', to='investigations.subtask')),
                ('parent_thought', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_thoughts', to='agents.thoughtchain')),
            ],
            options={
                'db_table': 'thought_chains',
                'ordering': ['sequence_number', 'timestamp'],
                'indexes': [models.Index(fields=['investigation', 'sequence_number'], name='thought_cha_investi_8837f4_idx'), models.Index(fields=['investigation', 'timestamp'], name='thought_cha_investi_28b04c_idx')],
            },
        ),
    ]
