# reports/models.py

from django.db import models
import uuid


class Report(models.Model):
    """Investigation reports generated by AI"""
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    investigation = models.ForeignKey(
        'investigations.Investigation',
        on_delete=models.CASCADE,
        related_name='reports'
    )
    
    REPORT_TYPE_CHOICES = [
        ('executive_summary', 'Executive Summary'),
        ('full_report', 'Full Report'),
        ('entity_profile', 'Entity Profile'),
    ]
    report_type = models.CharField(max_length=30, choices=REPORT_TYPE_CHOICES)
    
    title = models.CharField(max_length=300)
    content = models.TextField(help_text="Report content in Markdown format")
    
    FORMAT_CHOICES = [
        ('markdown', 'Markdown'),
        ('pdf', 'PDF'),
        ('html', 'HTML'),
    ]
    format = models.CharField(max_length=20, choices=FORMAT_CHOICES, default='markdown')
    
    file_path = models.FileField(upload_to='reports/%Y/%m/%d/', null=True, blank=True)
    version = models.IntegerField(default=1)
    
    generated_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'reports'
        ordering = ['-generated_at']
        indexes = [
            models.Index(fields=['investigation', 'report_type']),
        ]
    
    def __str__(self):
        return f"{self.title} - v{self.version}"