# Generated by Django 5.2.11 on 2026-02-07 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('initial_query', models.TextField(help_text='Original research question')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('current_phase', models.CharField(choices=[('planning', 'Planning'), ('researching', 'Researching'), ('analyzing', 'Analyzing'), ('reporting', 'Reporting')], default='planning', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_completion', models.DateTimeField(blank=True, null=True)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investigations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('research_strategy', models.JSONField(default=list, help_text='List of planned research steps')),
                ('hypothesis', models.TextField(blank=True)),
                ('priority_areas', models.JSONField(default=list)),
                ('avoided_paths', models.JSONField(default=list, help_text='Dead ends to skip')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='investigations.investigation')),
            ],
            options={
                'db_table': 'investigation_plans',
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('web_search', 'Web Search'), ('document_analysis', 'Document Analysis'), ('entity_extraction', 'Entity Extraction'), ('relationship_mapping', 'Relationship Mapping')], max_length=30)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result', models.JSONField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('order', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='investigations.investigation')),
                ('parent_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='investigations.subtask')),
            ],
            options={
                'db_table': 'subtasks',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['user', 'status'], name='investigati_user_id_ec09b1_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['status', 'current_phase'], name='investigati_status_ae318d_idx'),
        ),
        migrations.AddIndex(
            model_name='subtask',
            index=models.Index(fields=['investigation', 'status'], name='subtasks_investi_989535_idx'),
        ),
    ]
