# Generated by Django 5.2.11 on 2026-02-07 19:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_type', models.CharField(choices=[('executive_summary', 'Executive Summary'), ('full_report', 'Full Report'), ('entity_profile', 'Entity Profile')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='Report content in Markdown format')),
                ('format', models.CharField(choices=[('markdown', 'Markdown'), ('pdf', 'PDF'), ('html', 'HTML')], default='markdown', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='reports/%Y/%m/%d/')),
                ('version', models.IntegerField(default=1)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='investigations.investigation')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['investigation', 'report_type'], name='reports_investi_4fb873_idx')],
            },
        ),
    ]
