# Generated by Django 5.2.11 on 2026-02-07 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('person', 'Person'), ('company', 'Company'), ('location', 'Location'), ('event', 'Event'), ('document', 'Document'), ('financial_instrument', 'Financial Instrument')], max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('aliases', models.JSONField(default=list, help_text='Alternative names')),
                ('description', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_count', models.IntegerField(default=0, help_text='Number of sources mentioning this entity')),
                ('metadata', models.JSONField(default=dict, help_text='Type-specific information')),
                ('position_x', models.FloatField(blank=True, null=True)),
                ('position_y', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovered_by_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.subtask')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='investigations.investigation')),
            ],
            options={
                'db_table': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(choices=[('owns', 'Owns'), ('works_for', 'Works For'), ('connected_to', 'Connected To'), ('transacted_with', 'Transacted With'), ('located_in', 'Located In'), ('parent_of', 'Parent Of')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=0.0)),
                ('strength', models.FloatField(default=0.5, help_text='Relationship strength for visualization')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovered_by_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.subtask')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='investigations.investigation')),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='entities.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='entities.entity')),
            ],
            options={
                'db_table': 'relationships',
            },
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['investigation', 'entity_type'], name='entities_investi_033d65_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['name'], name='entities_name_f90948_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('investigation', 'name', 'entity_type')},
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['investigation', 'relationship_type'], name='relationshi_investi_8be099_idx'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['source_entity', 'target_entity'], name='relationshi_source__380a5b_idx'),
        ),
    ]
