# Generated by Django 5.2.11 on 2026-02-07 14:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0001_initial'),
        ('investigations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evidence_type', models.CharField(choices=[('document', 'Document'), ('web_page', 'Web Page'), ('image', 'Image'), ('video', 'Video'), ('testimony', 'Testimony'), ('financial_record', 'Financial Record')], max_length=30)),
                ('title', models.CharField(max_length=300)),
                ('content', models.TextField(help_text='Extracted or summarized content')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('source_credibility', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('unverified', 'Unverified')], default='unverified', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Publication date, author, etc.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discovered_by_task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investigations.subtask')),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='investigations.investigation')),
            ],
            options={
                'db_table': 'evidence',
            },
        ),
        migrations.CreateModel(
            name='EvidenceEntityLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relevance', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('mentioned', 'Mentioned')], max_length=20)),
                ('quote', models.TextField(blank=True, help_text='Specific quote linking them', null=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='entities.entity')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_links', to='evidence.evidence')),
            ],
            options={
                'db_table': 'evidence_entity_links',
            },
        ),
        migrations.CreateModel(
            name='EvidenceRelationshipLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('supports', models.BooleanField(help_text='True if supports, False if contradicts')),
                ('strength', models.FloatField(default=0.5, help_text='How strongly it supports/contradicts')),
                ('quote', models.TextField(blank=True, null=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_links', to='evidence.evidence')),
                ('relationship', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='entities.relationship')),
            ],
            options={
                'db_table': 'evidence_relationship_links',
            },
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['investigation', 'evidence_type'], name='evidence_investi_a61bd4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='evidenceentitylink',
            unique_together={('evidence', 'entity')},
        ),
        migrations.AlterUniqueTogether(
            name='evidencerelationshiplink',
            unique_together={('evidence', 'relationship')},
        ),
    ]
